springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc.html
spring:
  application:
    name: "rbcs"
  datasource:
    url: jdbc:mysql://localhost:3306/rbcs?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      connection-timeout: 3000
      auto-commit: true
      idle-timeout: 500000
      initialization-fail-timeout: 1
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    database: mysql
  data:
    redis:
      host: localhost
  cloud:
    aws:
      sqs:
        enabled: false