springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc.html
spring:
  application:
    name: "rbcs"
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/rbcs?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      connection-timeout: 3000
      auto-commit: true
      idle-timeout: 500000
      initialization-fail-timeout: 1
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        cache:
          use_query_cache: true
          use_second_level_cache: true
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory
          redisson:
            fallback: true
            config: redisson.yaml
    open-in-view: false
    show-sql: true
    database: mysql
  cloud:
    aws:
      sqs:
        enabled: true
  redis:
    redisson:
      file: classpath:redisson.yaml
events:
  queues:
    transaction-execution-queue: transaction-execution-queue
