apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbcs
  labels:
    app: rbcs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rbcs
  template:
    metadata:
      labels:
        app: rbcs
    spec:
      containers:
      - name: rbcs
        image: 255170271587.dkr.ecr.ap-northeast-1.amazonaws.com/luhui/rbcs:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: rds-config
              key: host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: rds-config
              key: port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: rds-config
              key: dbname
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: rds-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rds-credentials
              key: password
        - name: AWS_REGION
          value: ap-northeast-1
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret_access_key
        imagePullPolicy: Always